import 
{
  CreditCardOutlined,
  FormOutlined,
  MenuUnfoldOutlined,
  GroupOutlined,
  TabletOutlined,
  CheckSquareOutlined,
  FieldTimeOutlined,
  FrownOutlined,
  DoubleRightOutlined,
  FileTextOutlined,
  FieldNumberOutlined,
  TrademarkCircleOutlined,
  EditOutlined,
  CloudDownloadOutlined,
  TableOutlined,
  BoxPlotOutlined,
  LinkedinOutlined,
  MinusSquareOutlined,
  UserOutlined,
  ClusterOutlined,
  UnorderedListOutlined,
  SmallDashOutlined,
  CodeSandboxOutlined,
  ShakeOutlined,
  CodepenCircleOutlined,
  ExperimentOutlined,
  FilterOutlined,
  GlobalOutlined
} from '@ant-design/icons';

const componentIconMap = {
  XinCard: CreditCardOutlined,
  XinForm: FormOutlined,
  XinMenu: MenuUnfoldOutlined,
  XinRadioGroup: GroupOutlined,
  XinButton: TabletOutlined,
  XinCheckBox: CheckSquareOutlined,
  XinDatePicker: FieldTimeOutlined,
  XinIcon: FrownOutlined,
  XinInput: DoubleRightOutlined,
  XinLable: FileTextOutlined,
  XinNumber: FieldNumberOutlined,
  XinRadio: TrademarkCircleOutlined,
  XinRate: EditOutlined,
  XinUpload: CloudDownloadOutlined,
  XinTable: TableOutlined,
  XinFlex: BoxPlotOutlined,
  XinLink: LinkedinOutlined,
  XinDiv: MinusSquareOutlined,
  XinCarousel: CreditCardOutlined,
  XinAvatar: UserOutlined,
  XinTabs: ClusterOutlined,
  XinList: UnorderedListOutlined,
  XinListItem: SmallDashOutlined,
  XinBoxGeometry: CodeSandboxOutlined,
  XinCapsuleGeometry: ShakeOutlined,
  XinCircleGeometry: CodepenCircleOutlined,
  XinConeGeometry: ExperimentOutlined,
  XinCylinderGeometry: FilterOutlined,
  XinDodecahedronGeometry: GlobalOutlined
}

const componentTextMap = {
  XinCard: '卡片',
  XinForm: '表单',
  XinMenu: '菜单',
  XinRadioGroup: '单选栏',
  XinButton: '按钮',
  XinCheckBox: '多选按钮',
  XinDatePicker: '日期框',
  XinIcon: '图标',
  XinInput: '输入框',
  XinLable: '标签',
  XinNumber: '数值框',
  XinRadio: '单选框',
  XinRate: '评分',
  XinUpload: '图片上传',
  XinTable: '表格',
  XinFlex: 'Flex布局',
  XinLink: '页面跳转',
  XinDiv: '空div',
  XinCarousel: '轮播图',
  XinAvatar: '头像',
  XinTabs: '多页签',
  XinList: '列表',
  XinListItem: '列表项',
  XinBoxGeometry: '长方体',
  XinCapsuleGeometry: '胶囊',
  XinCircleGeometry: '圆形缓冲',
  XinConeGeometry: '圆锥体',
  XinCylinderGeometry: '圆柱体',
  XinDodecahedronGeometry: '十二面体'
}

export {
  componentIconMap,
  componentTextMap
}
