const attributeValueMap = {
  attributeValue: '属性值',
  size: '大小',
  disabled: '是否禁用',
  addonBefore: '前置标签',
  addonAfter: '后置标签',
  placeholder: '默认提示',
  url: 'URL地址',
  openType: '新页签打开',
  listItemNum: '子元素',
  title: '标题',
  buttonType: '按钮类型',
  size: '组件大小',
  danger: '危险按钮',
  ghost: '幽灵按钮',
  prefix: '前缀',
  suffix: '后缀',
  allowClear: '允许清除',
  showCount: '展示字数',
  checked: '是否选中',
  label: '标签',
  layout: '布局',
  required: '必填',
  requiredMessage: '必填提示',
  colon: '标题冒号',
  labelAlign: '标题对齐方式',
  iconType: '图标类型',
  twoToneColor: '主题色',
  rotate: '旋转角度',
  mode: '菜单类型',
  visible: '隐藏',
  picker: '日期类型',
  showTime: '展示时间',
  dateFormat: '日期格式',
  attributeValueNumber: '属性值',
  max: '最大值',
  min: '最小值',
  step: '步数大小',
  optionType: '单选类型',
  buttonStyle: '按钮风格',
  selectedID: '选中节点ID',
  allowHalf: '允许半选',
  count: 'star总数',
  disabled: '禁用',
  bordered: '边框',
  setColumns: '表头字段',
  setTableData: '表格内容',
  showHeader: '禁用表头',
  selectedKey: '选中菜单key',
  pageUrl: '页面ID',
  autoplay: '自动切换',
  src: '资源地址',
  shape: '形状',
  activeKey: '当前key',
  animated: '开启动画',
  centered: '标签居中',
  tabBarGutter: '页签间隙',
  tabPosition: '页签位置',
  tabsType: '页签样式',
  description: '描述',
  setIcon: '选择图标',
  inputType: '类型',
  //样式类型
  fontSize:'字体大小',
  width:'宽度',
  height: '高度',
  maxWidth: '最大宽度',
  maxHeight: '最大高度',
  color: '字体颜色',
  backgroundColor: '背景颜色',
  marginLeft: '左边距',
  marginTop: '上边距',
  lineHeight: '行高',
  //3D
  x: 'x轴',
  y: 'y轴',
  z: 'z轴',
  width3d:'长度',
  height3d:'宽度',
  depth3d: '高度',
  radius3d: '半径',
  length3d: '长度',
  capSegments: '曲线个数',
  radialSegments: '分离面数',
  segments: '三角面数',
  radiusTop: '顶部半径',
  radiusBottom: '底部半径',
  detail: '顶点倍数'
}

export default attributeValueMap